apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dev-sample-argocd
  name: orbstack-host-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/data